# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 13e78540772f874e5135b04e8b9b4570dfcccc422fad0ac1055a14269cc2bae10b5aef1b712fa133c14e0360e90d580e0d9692bf53d4d889e62a5cd690cd8bff

test:
  secret_key_base: 57d7ad5b25af8810c46a6c58a928be74fc6f469bf984dabf462df18a4b1720f67f829c6174f788e88ec39b7421470fabe4ab6510ad25d433cb3e4d7b1a68872e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
